// app/head.tsx
export default function Head() {
    return (
      <>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </>
    );
  }
  